# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/processor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_processorWindow(object):
    def setupUi(self, processorWindow):
        processorWindow.setObjectName("processorWindow")
        processorWindow.resize(761, 282)
        self.centralwidget = QtWidgets.QWidget(processorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 50, 421, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 421, 191))
        self.groupBox.setObjectName("groupBox")
        self.teLog = QtWidgets.QTextEdit(self.groupBox)
        self.teLog.setGeometry(QtCore.QRect(10, 20, 401, 161))
        self.teLog.setReadOnly(True)
        self.teLog.setObjectName("teLog")
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        self.pbStop.setGeometry(QtCore.QRect(300, 10, 131, 31))
        self.pbStop.setObjectName("pbStop")
        self.lcdCurrentPage = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdCurrentPage.setGeometry(QtCore.QRect(70, 10, 64, 31))
        self.lcdCurrentPage.setStyleSheet("QLCDNumber {\n"
"  color: rgb(0, 170, 255);\n"
"}")
        self.lcdCurrentPage.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdCurrentPage.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdCurrentPage.setObjectName("lcdCurrentPage")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 71, 31))
        self.label_2.setObjectName("label_2")
        self.lcdSavedNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdSavedNumber.setGeometry(QtCore.QRect(220, 10, 64, 31))
        self.lcdSavedNumber.setStyleSheet("QLCDNumber {\n"
"  color: rgb(0, 170, 0);\n"
"}")
        self.lcdSavedNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdSavedNumber.setProperty("value", 0.0)
        self.lcdSavedNumber.setObjectName("lcdSavedNumber")
        self.teLogDebug = QtWidgets.QTextEdit(self.centralwidget)
        self.teLogDebug.setGeometry(QtCore.QRect(440, 0, 321, 281))
        self.teLogDebug.setStyleSheet("QTextEdit {\n"
"  background-color: rgb(0, 0, 0);\n"
"}")
        self.teLogDebug.setReadOnly(True)
        self.teLogDebug.setObjectName("teLogDebug")
        processorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(processorWindow)
        QtCore.QMetaObject.connectSlotsByName(processorWindow)

    def retranslateUi(self, processorWindow):
        _translate = QtCore.QCoreApplication.translate
        processorWindow.setWindowTitle(_translate("processorWindow", "智赢跨境 自动化"))
        self.groupBox.setTitle(_translate("processorWindow", "运行日志"))
        self.pbStop.setText(_translate("processorWindow", "停止任务"))
        self.label.setText(_translate("processorWindow", "当前页码"))
        self.label_2.setText(_translate("processorWindow", "已保存数量"))
