# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/processor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_processorWindow(object):
    def setupUi(self, processorWindow):
        processorWindow.setObjectName("processorWindow")
        processorWindow.resize(521, 282)
        self.centralwidget = QtWidgets.QWidget(processorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 50, 501, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 501, 191))
        self.groupBox.setObjectName("groupBox")
        self.teLog = QtWidgets.QTextEdit(self.groupBox)
        self.teLog.setGeometry(QtCore.QRect(10, 20, 481, 161))
        self.teLog.setReadOnly(True)
        self.teLog.setObjectName("teLog")
        self.ptStop = QtWidgets.QPushButton(self.centralwidget)
        self.ptStop.setGeometry(QtCore.QRect(360, 10, 151, 31))
        self.ptStop.setObjectName("ptStop")
        self.ptPause = QtWidgets.QPushButton(self.centralwidget)
        self.ptPause.setGeometry(QtCore.QRect(200, 10, 151, 31))
        self.ptPause.setObjectName("ptPause")
        self.lcdCurrentPage = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdCurrentPage.setGeometry(QtCore.QRect(70, 10, 64, 31))
        self.lcdCurrentPage.setObjectName("lcdCurrentPage")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 31))
        self.label.setObjectName("label")
        processorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(processorWindow)
        QtCore.QMetaObject.connectSlotsByName(processorWindow)

    def retranslateUi(self, processorWindow):
        _translate = QtCore.QCoreApplication.translate
        processorWindow.setWindowTitle(_translate("processorWindow", "智赢跨境 自动化"))
        self.groupBox.setTitle(_translate("processorWindow", "运行日志"))
        self.ptStop.setText(_translate("processorWindow", "停止任务"))
        self.ptPause.setText(_translate("processorWindow", "暂停任务"))
        self.label.setText(_translate("processorWindow", "当前页码"))
