# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qr_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QRLoginWindow(object):
    def setupUi(self, QRLoginWindow):
        QRLoginWindow.setObjectName("QRLoginWindow")
        QRLoginWindow.resize(353, 423)
        self.centralwidget = QtWidgets.QWidget(QRLoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qr_label = QtWidgets.QLabel(self.centralwidget)
        self.qr_label.setGeometry(QtCore.QRect(20, 20, 311, 251))
        self.qr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_label.setObjectName("qr_label")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(20, 310, 311, 16))
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.refresh_btn = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_btn.setGeometry(QtCore.QRect(20, 370, 311, 41))
        self.refresh_btn.setObjectName("refresh_btn")
        QRLoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(QRLoginWindow)
        QtCore.QMetaObject.connectSlotsByName(QRLoginWindow)

    def retranslateUi(self, QRLoginWindow):
        _translate = QtCore.QCoreApplication.translate
        QRLoginWindow.setWindowTitle(_translate("QRLoginWindow", "MainWindow"))
        self.qr_label.setText(_translate("QRLoginWindow", "二维码加载中..."))
        self.status_label.setText(_translate("QRLoginWindow", "等待获取二维码"))
        self.refresh_btn.setText(_translate("QRLoginWindow", "重新获取二维码"))
